language:
  - erlang

opt-release:
  - 22.0
  - 21.0
  - 20.0
  - 19.0
  - 18.0 

addons:
  apt:
    packages:
      - libxml2-dev
      - python3
      - python3-pip

before_install:
  - pip3 install pyang
  - cd ..
  - git clone https://github.com/hawk/lux.git
  - cd lux
  - export PATH=$PATH:$(pwd)/bin
  - autoconf
  - ./configure
  - make
  - cd ..

script:
  - cd yanger
  - source env.sh
  - make
  - make test
